### PR TITLE
Added Block and Unblock commands, fixed config.json example

### LINKED ISSUE #149: Move the Profanity Filter to a Database
I thought it might be worth moving this feature to a database as well so that we're able to add and remove terms as necessary.

This would require creating a command like !profanity add/remove to allow for edits within the server.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Yes! I spent the last two hours debugging and fixing things! Hope you merge my pull request!

File: events/message.js [hunk 1]
```diff
@@ -7,30 +9,62 @@ const profanityActions = require('../eventActions/profanityActions');
...
-
+      client.commands.get(command) ||
+      client.commands.get(client.aliases.get(command));
 		if (commandfile) {
 			commandfile.execute(client, message, args).then(() => {
 				message.delete(1500);
 			}); // Execute found command
 		}
+		if (!commandfile) {
+			if (bannedWords.some((word) => message.content.includes(word))) {
```
Comment (ghost) [inline events/message.js]: Banned words check here should go in `eventActions/profanityActions.js`, not `message.js`

**Review by ghost — CHANGES_REQUESTED** [review]
Everything else looks good!

**Comment by ghost** [comment]
Also, make sure this doesn't continue to use the filter array in config.json

File: events/message.js (hunk 1 above)
Comment (ghost) [reply events/message.js]: ok!

**Comment by ghost** [comment]
Fixed Code as you guys stated!

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
resolve the merge conflict and then i can merge everything in :D
