### PR TITLE
Modify regex for reflection matching

### LINKED ISSUE #333: [BUG REPORT] Horace is not catching bold/italic versions of the word Reflection
---
name: Bug report
about: Horace
title: 'Horace is not catching bold/italic versions of the word Reflection'
labels: ''
assignees: ''

---

**Please Describe Your Issue**
Horace is not catching bold/italic versions of the word Reflection

**How to Reproduce**
Please tell us how this error came about.
1. Have the bot running
2. Write *Horace*

**Expected behavior**
It should add a 🛡️. It's not.

**Discord Information**
 - Are you updated to the most recent version of Discord? Web version, so yes
 - Are you on mobile or browser? browser

**Smartphone (please complete the following information):**
 - Device: PC
 - OS: Fedora Linux 43
 - Browser: Brave
 - Version: 1.87

### PR DESCRIPTION
**Pull request by mimi2626**
Updated regex to allow for formatting characters before 'reflection'.

### CODE REVIEW

File: eventActions/reactions.js [hunk 1]
```diff
@@ -50,9 +50,9 @@ const handleReactions = async function(client, message, isCommand) {
 			message,
 			Config.CHANNELS.COTW,
 			Config.EMOTES.COTW_REFLECTION,
-			// Match 0 - n instances of a word followed by space, followed by "reflection".
+			// Match 0 - n instances of a word followed by a space, followed by "reflection".
 			// This tests if "reflection" is present in the first n words of the string.
-			new RegExp(`^(\\w+\\s+){0,${Config.REFLECTION_CHECK_DEPTH - 1}}(reflection)`, 'i')
+			new RegExp(`^(\\w+\\s+){0,${Config.REFLECTION_CHECK_DEPTH - 1}}[*_~]*(reflection)`, 'i')
```
Comment (catalincodes) [inline eventActions/reactions.js:55]: This is good, but it can be better:

new RegExp(`^(\\w+\\s+){0,${Config.REFLECTION_CHECK_DEPTH - 1}}[*_~]*(reflection)\\b[*_~]*`, 'i')

This way we ensure that

Reflectionless is not allowed, but *Reflection* is allowed

Comment (catalincodes) [reply eventActions/reactions.js:55]: As per @mimi2626 ,

with the change I proposed, which adds a word boundary, we would block "reaction!" or "reactionnnn" which can totally happen. 

I agree that it may be fine to allow these.

**Review by catalincodes — APPROVED** [review]

File: eventActions/reactions.js (hunk 1 above)
Comment (catalincodes) [reply eventActions/reactions.js:55]: @cjtheham I am assigning you to merge it. So you can have a say and leave your 2 cents.

Comment (cjtheham) [reply eventActions/reactions.js:55]: I'm fine to allow this even allowing `reflectionless` - I think that it's a rare side-case and that as long as we're allowing punctuation and styling that's what really matters.

**Comment by cjtheham** [comment]
Pushing this live to the server now - thank you so much for the contribution @mimi2626!
